[project]
name = "covid-variant-pipeline"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Becky Sweger", email = "rsweger@umass.edu"},
]
dependencies = [
    "snakemake>=8.11.0",
    "pandas>=2.2.2",
    "toml>=0.10.2",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"


[tool.pdm]
distribution = true

[tool.ruff]
line-length = 120
lint.extend-select = ['I']
