name: Run tests for target data script
permissions:
  contents: read

on:
  push:
    paths:
      - 'src/get_target_data.py'
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Python 🐍
        uses: actions/setup-python@v5
        with:
          cache: pip
          python-version: '3.12'

      - name: Install dependencies 📦️
        run: |
          pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Run tests 🧪
        run: |
          pytest src/get_target_data.py -s
