name: Hub Config Validation (R)
permissions:
  contents: read
  pull-requests: write


on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths:
      - 'hub-config/**'
      - '!**README**'

jobs:
  validate-hub-config:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
      HUB_PATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@bd49c52ffe281809afa6f0fecbf37483c5dd0b93  #v2.11.3
        with:
          install-r: true
          use-public-rspm: true
          extra-repositories: 'https://hubverse-org.r-universe.dev'

      - name: Update R
        run: |
          sudo apt-get update

      - uses: r-lib/actions/setup-r-dependencies@bd49c52ffe281809afa6f0fecbf37483c5dd0b93  #v2.11.3
        with:
          cache: 'always'
          packages: |
            any::hubAdmin
            any::sessioninfo

      - name: Run validations
        id: validate
        run: hubAdmin::ci_validate_hub_config(diff = "${{ runner.temp }}/diff.md")
        shell: Rscript {0}
      - name: "Comment on PR"
        id: comment-diff
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: carpentries/actions/comment-diff@570d80c0a93d14fbe400a146011fbaa3ae3b6ae8  #v0.16.0
        with:
          pr: ${{ env.PR_NUMBER }}
          path: ${{ runner.temp }}/diff.md
      - name: Error on Failure
        if: ${{ steps.validate.outputs.result == 'false' }}
        run: |
          echo "::error title=Invalid Configuration::Errors were detected in one or more config files in 'hub-config/'"
          exit 1

